### PR TITLE
Add foreign definitions for v9.0.1

### PR DESCRIPTION
**Pull request by anttih**
Noteworthy things:

* `toStringWith` precision and exponent versions are not compatible with JS version.
* `toStringWith` fixed kind of works but keeps the dot suffix in the output because this is valid Chez syntax for a flonum literal.
* `toString` does not remove the zero decimal from the output because a literal without a decimal dot is not valid syntax for a flonum, and would  be converted to a `fixnum` at runtime and then throw an exception when used with `fl*` operators.

### CODE REVIEW

**Comment by anttih** [comment]
I can't figure out how to implement the `Number.Format` stuff. There is `format` but it doesn't provide all the functionality and is awkward to use when you have to dynamically form the format string.

**Comment by anttih** [comment]
The package set ref is not correct and is pending on a PR to the purescm package-set.

**Review by f-f — APPROVED** [review]

**Comment by anttih** [comment]
@f-f how did the package-set hash not change for my latest commit? Isn't the hash based on the contents of the package-set json file?

**Comment by f-f** [comment]
@anttih just like in Nix, if the hash is there and it's contained in the store, then Spago will not try to fetch the URL. You can remove the hash to make it fetch the new thing, Spago will put the new one there.

**Comment by anttih** [comment]
I forgot that the json file _is_ actually the same since I had used the ref to the PR that had the correct stuff.

**Comment by anttih** [comment]
I also forgot the CI config :)

**Pull request merged**
